/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.tallerprogra;

import java.util.Scanner;

public class App {
    
            public static void main(String[] args) {
             Scanner sc = new Scanner(System.in);

             // Convertir Celsius a Fahrenheit

             System.out.println("Ingrese el valor de grados celsius");//guardando el valor
             double celsius = sc.nextDouble();

             //realizar la operacion
             double fahrenheit = (celsius*9/5)+32;
             // hola
             System.out.println("El valor de grados fahrenheit es: "+fahrenheit);
             //holaA
                System.out.println("hola mundo");
                System.out.println("bienvenidos");
                System.out.println("waos");
    }

    }