// hola que tal tarea modificado por adrian y genesis 
/*// PROGRAMA PARA CALCULAR GRADOS CELCIUS A FARENHEIT
 * This source file was generated by the Gradle 'init' task
 */
package com.example.tallerprogra;

import java.util.Scanner;
public class App {
            //Librería
            public static void main(String[] args) {
             Scanner sc = new Scanner(System.in);
                System.out.println("CONVERSIONES DE CELSIUS A FAHRENHEIT");
             // Convertir Celsius a Fahrenheit

             System.out.println("Ingrese el valor de grados celsius");//guardando el valor
             double celsius = sc.nextDouble();
                System.out.println("REALIZACION DE OPERACIONES");
                System.out.println("la operacion que se va a realizar en primero una multiplicacion");
                System.out.println("luego se realiza una suma en base a la formula ");
             //realizar la operacion
             // hola que tal ing 
             double fahrenheit = (celsius*9/5)+32;

             System.out.println("El resultado de grados fahrenheit es: "+fahrenheit);//resultado
             System.out.println("Hola cambios genesis");   
             //fin del programa
                System.out.println("GRACIAS POR USAR ESTE PEQUEÑO PROGRAMA");
    }

    }