// hola que tal tarea modifucada por adrian y henesis 
/*// PROGRAMA PARA CALCULAR GRADOS CELCIUS A FARENHEIT
 * This source file was generated by the Gradle 'init' task
 */
package com.example.tallerprogra;

import java.util.Scanner;

public class App {
            //Librería
            public static void main(String[] args) {
             Scanner sc = new Scanner(System.in);

             // Convertir Celsius a Fahrenheit

             System.out.println("Ingrese el valor de grados celsius");//guardando el valor
             double celsius = sc.nextDouble();

             //realizar la operacion
             double fahrenheit = (celsius*9/5)+32;

             System.out.println("El resultado de grados fahrenheit es: "+fahrenheit);//resultado
             System.out.println("Hola cambios genesis");   
    }

    }